images:
  applogic: rubykube/applogic:latest
  arke: quay.io/openware/arke:2.6.0-bccb72c
  superset: amancevice/superset:0.28.1
superset:
  email: superset-admin@openware.com
  username: admin
  password: changeme
arke:
  log_level: INFO
  accounts:
  - id: 1
    driver: bitfaker
    debug: false
    host: "http://www.brandlovers.co.za"
    ws: "ws://www.brandlovers.co.za"
    key: "fa45a30e94b1eb1c"
    secret: "6dfdb515791ef72a4e24dae497ae925f"
    delay: 1

  - id: 2
    driver: bitfaker
    host: "api.bitfinex.com"
    key: "GGMcaLoDdl128x0KMFDzGLptLFlKCh39JRlE9r7vNPf"
    secret: "ZcfHsJKzUV8JwtNYg82OQ9QgMvzYjraT1DSki8mMwoM"
    delay: 1

  strategies:
  - id: 1
    type: copy
    debug: true
    enabled: true
    period: 10
    params:
      spread_bids: 0.003
      spread_asks: 0.003
      limit_asks_base: 0.05
      limit_bids_base: 0.05
      levels_size: 0.25
      levels_count: 10
      side: both
      enable_orderback: false
    target:
      account_id: 1
      market:
        id: ETHUSD
        base: btc
        quote: usd
        base_precision: 2
        quote_precision: 2
        min_ask_amount: 1.5
        min_bid_amount: 1.5
    sources:
    - account_id: 2
      market:
        id: ETHUSD
        base: BTC
        quote: USD
        base_precision: 8
        quote_precision: 8
        min_order_back_amount: 1.5

  - id: 2
    type: microtrades
    debug: true
    period: 5
    period_random_delay: 10
    params:
      linked_strategy_id: 1
      min_amount: 0.05
      max_amount: 10
      min_price: 100
      max_price: 1000
    target:
        account_id: 1
        market:
          id: ETHUSD
          base: eth
          quote: usd
          base_precision: 2
          quote_precision: 2
          min_ask_amount: 1.5
          min_bid_amount: 1.5
    strategy:
      type: copy
      volume_ratio: 0.1
      target:
        driver: rubykube
        market: 'ETHUSD'
        host: "http://www.brandlovers.co.za"
        key: ""
        secret: ""
        rate_limit: 1
      sources:
        - driver: bitfinex
          market: 'ETHUSD'
          host: "api.bitfinex.com"
          key: "GGMcaLoDdl128x0KMFDzGLptLFlKCh39JRlE9r7vNPf"
          secret: "ZcfHsJKzUV8JwtNYg82OQ9QgMvzYjraT1DSki8mMwoM"
          rate_limit: 0.2

